<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-G7LJERD" ignored="0" name="Postive Scenarios - 1" tests="5" failures="3" timestamp="27 May 2019 09:22:37 GMT" time="264.218" errors="0">
  <testcase name="Test1" time="22.467" classname="com.test.PefinWebApp.TestNgDriver"/>
  <testcase name="Test2" time="22.447" classname="com.test.PefinWebApp.TestNgDriver"/>
  <testcase name="Test3" time="26.464" classname="com.test.PefinWebApp.TestNgDriver">
    <failure type="java.lang.AssertionError" message="ERROR expected [$242,979] but found [$239,182]">
      <![CDATA[java.lang.AssertionError: ERROR expected [$242,979] but found [$239,182]
at com.test.PefinWebApp.YourNewHomePlan.<init>(YourNewHomePlan.java:34)
at com.test.PefinWebApp.TestNgDriver.Test3(TestNgDriver.java:69)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="Test4" time="22.62" classname="com.test.PefinWebApp.TestNgDriver">
    <failure type="java.lang.AssertionError" message="ERROR expected [$242,979] but found [$233,443]">
      <![CDATA[java.lang.AssertionError: ERROR expected [$242,979] but found [$233,443]
at com.test.PefinWebApp.YourNewHomePlan.<init>(YourNewHomePlan.java:34)
at com.test.PefinWebApp.TestNgDriver.Test4(TestNgDriver.java:80)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase name="Test5" time="24.198" classname="com.test.PefinWebApp.TestNgDriver">
    <failure type="java.lang.AssertionError" message="ERROR expected [$242,979] but found [$233,443]">
      <![CDATA[java.lang.AssertionError: ERROR expected [$242,979] but found [$233,443]
at com.test.PefinWebApp.YourNewHomePlan.<init>(YourNewHomePlan.java:34)
at com.test.PefinWebApp.TestNgDriver.Test5(TestNgDriver.java:92)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test5 -->
</testsuite> <!-- Postive Scenarios - 1 -->
